create schema TEST;

--TEST.TEST_VIEW_ENTITY
CREATE TABLE TEST.TEST_VIEW_ENTITY (
	ID 					VARCHAR(36) NOT NULL,
	VERSION 			BIGINT NOT NULL,
	SERIALIZED_DATA 	BLOB(1048576),
	ITEM_ID 			VARCHAR(36) NOT NULL,
	KEY					VARCHAR(36),
	OTHER_KEY	 		VARCHAR(36)
);

CREATE UNIQUE INDEX TEST.TEST_VIEW_ENTITY_PK
	ON TEST.TEST_VIEW_ENTITY (ID);

ALTER TABLE TEST.TEST_VIEW_ENTITY 
	ADD CONSTRAINT RATE_VIEW_ENTITY_V1_PK 
		PRIMARY KEY (ID);
		
CREATE INDEX TEST.TEST_VIEW_ENTITY_ITEM_ID_IDX
	ON TEST.TEST_VIEW_ENTITY (ITEM_ID);

CREATE INDEX TEST.TEST_VIEW_ENTITY_KEY_IDX
	ON TEST.TEST_VIEW_ENTITY (KEY);

CREATE INDEX TEST.TEST_VIEW_ENTITY_OTHER_KEY_IDX
	ON TEST.TEST_VIEW_ENTITY (OTHER_KEY);
